### ISSUE TITLE
Feature request: Add option for default save path(s)

### ISSUE THREAD

**Issue by Torkiliuz** [porla/porla#105]
There should be a way for the user to configure multiple default save paths, so they can be selected from a dropdown list when manually adding torrents

**Comment by vktr** [comment]
I like it.

**Comment by vktr** [comment]
I fixed a few bugs in presets the last day or so which makes them work better in the add torrent dialog. You can use presets to set default save paths (and other things).

Set up two presets,

```toml
[presets.default]
save_path = "/downloads"

[presets.other]
save_path = "/tmp"
```

The add torrent dialog will now show a preset drop down for `default` and `other` and switching between them will update the save path as well. You can use presets for setting other things as well, but that's the gist of it. Refer to [the documentation for presets](https://porla.org/configuration#presets) to learn more!

Closing this if that feels OK.
