### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by sachaw** [porla/porla#118]
Finally came across your project, exactly what I've been looking for.
My setup requires me to use RSS feeds to automate a number of "subscriptions".

Is this something that you would consider in-scope and would support, or should I write an external tool to handle my use case?
Thanks.

**Comment by vktr** [comment]
I have considered it but haven't had the time to decide if it is in scope or not :smiley: Until then, you might be interested in [autobrr](https://github.com/autobrr/autobrr) which handles RSS feeds and indexers very well.

**Comment by sachaw** [comment]
Many thanks, great recommendation.

**Comment by vktr** [comment]
Happy to help! I'll close this for now, since there's no current plan for RSS feeds.
