### ISSUE TITLE
Invalid RPC response

### ISSUE THREAD

**Issue by sachaw** [porla/porla#119]
The client library that I'm using to utilize the RPC methods is rejecting the response as non-conformant due to the lack of an `id` field, that's outlined as required as-per the spec: https://www.jsonrpc.org/specification#response_object:~:text=in%20section%205.1.-,id,-This%20member%20is

If I'm missing something, I'd love to know, or if you have any input or would accept a PR.
Thanks.

**Comment by vktr** [comment]
Thanks for the report! The RPC implementation is minimal effort so far - but the goal is to be compliant with JSONRPC 2.0. Give me a few hours and I'll improve the situation!

**Comment by sachaw** [comment]
Thanks! just a dummy `id` will suffice for now.

**Comment by vktr** [comment]
The issue should be resolved in the latest beta. If you run the Docker release, use the tag `beta-latest` or if you run the binary release the Github Action pipeline will produce artifacts here - https://github.com/porla/porla/actions/runs/4023332099
