### ISSUE TITLE
Can't access the WebUI when running in Docker

### ISSUE THREAD

**Issue by cstegmann** [porla/porla#147]
I can't seem to connect to the WebUI when running porla (Porla v0.34.0) in Docker. EIther on Linux or on Windows with Docker Desktop. Both machines are amd64.

The website exists for sure, I just can't seem to connect to it with localhost:1337

![image](https://user-images.githubusercontent.com/169027/229315639-d893a458-0e87-4c1c-8255-26d1670b4c4c.png)
![image](https://user-images.githubusercontent.com/169027/229315694-f13d6f7f-f2da-48b6-bb84-4a5b0f4fcb36.png)
![image](https://user-images.githubusercontent.com/169027/229315675-3ac892b6-7fe5-4d6a-870c-299b3eb5368a.png)
![image](https://user-images.githubusercontent.com/169027/229315685-47e1c1cc-3812-46e9-a8a0-77da1c10f046.png)

**Comment by vktr** [comment]
Hi @cstegmann! We actually had someone with the exact same issue just a day ago - it's an error on my end but can be solved by setting the `PORLA_HTTP_HOST` environment variable to `0.0.0.0`.

I'll make sure to set this as default for future Docker builds.

**Comment by cstegmann** [comment]
Thank you, I added "- PORLA_HTTP_HOST=0.0.0.0" to my docker compose and I can access the WebUI now.
