### ISSUE TITLE
How to fix No embedded web UI found?

### ISSUE THREAD

**Issue by paxter** [porla/porla#193]
First of all. Thanks for bringing up a new libtorrent based client with cross platform support! That is really great and the project looks awesome so far!

I just build porla like described in https://github.com/porla/porla#development

But there appears a warning about missing webui after starting the binary.

```
[...]
[2023-06-16 13:53:51.945689] [0x0000ffff8aa5c020] [info]    Running HTTP server on 127.0.0.1:1337
[2023-06-16 13:53:51.945797] [0x0000ffff8aa5c020] [info]    Enabling HTTP metrics endpoint
[2023-06-16 13:53:51.945819] [0x0000ffff8aa5c020] [info]    Enabling HTTP web UI
[2023-06-16 13:53:51.945876] [0x0000ffff8aa5c020] [warning] No embedded web UI found
```

Where I can find embedded WebUI?

Readme in https://github.com/porla/porla/tree/main/html writes something about additional webserver. I don't think that's what embedded web ui means.

After reading https://github.com/porla/porla/issues/145 it sounds the web ui have to build separately with `npm`?

I'm a little bit confused and can not find something related in any of the docs.

Please tell me how to fix that warning.

**Comment by vktr** [comment]
Hi!

Yeah, it should be clarified in the readme perhaps :smiley: So the web UI needs to be built separately if you want to build a complete binary, but it is not necessary to do it if you just want to do local development.

For local development you can ignore that warning, and instead go to the `html/` directory, run `npm i` and `npm run dev` then open up your browser at `localhost:5173`. The node dev server will proxy all the API requests to Porla.

If you want to build the binary with the web UI embedded, do something like this

```
cd html
npm i
npm run build
cd dist
zip -9 -r ../webui.zip *
```

Then run `make` (or `ninja`) again. The build process expects the `html/webui.zip` file to exist, and if it does, it embeds it in the application.

**Comment by paxter** [comment]
Thanks for replying.

I'm not interested into development. At least not currently. I'm just interested to prevent using of docker and wanted a single binary for running and testing some stuff.

I will try your second advise and update my building docs. Thanks for helping. :)

**Comment by vktr** [comment]
All the pipelines produce static binaries for arm64 and amd64 - here's the latest from main for example https://github.com/porla/porla/actions/runs/5242062776

**Comment by paxter** [comment]
Oh nice. Didn't see that arm64 static binary build support is already there. This should be much easier instead of self building each time. Thanks. :)
