### ISSUE TITLE
How to get tracker announce status/reply of torrents?

### ISSUE THREAD

**Issue by paxter** [porla/porla#203]
I'm wondering how it's possible to get `tracker status` of all or specific torrents. I checked https://porla.org/api/methods/torrents_list/ but could not find any field or method to getting the status.

Getting/Checking tracker status is important to know whether a torrent is properly working.

Is there any possibility to achieve that?

**Comment by vktr** [comment]
Does this method do what you want? `torrents.trackers.list` - https://porla.org/api/methods/torrents_trackers_list

**Comment by paxter** [comment]
Ah, I see. There is a list of objects in the `info_hashes` field. Neverming. Sorry for disturbing.

**Comment by vktr** [comment]
No problem 😃 The list of objects inte the `info_hashes` is if you have a torrent with both a v1 and v2 info hash, then you get information for both. In most cases I'd wager you only have a single item in that list though.
