### ISSUE TITLE
How to get last torrent activity?

### ISSUE THREAD

**Issue by f4n4t** [porla/porla#227]
First off, great project you have here. I really like it so far :)

Is it somehow possible to access the last activity time of a torrent?
The reason why I'm asking is that I remove torrents based on their last activity time when the space is running low.
In qBittorrent, this information was accessible through the API, but perhaps it's stored somewhere else and has nothing to do with libtorrent.
It would be nice to have this feature here, or maybe you have a better idea for a cleanup script.

**Comment by vktr** [comment]
Hi! Happy you like it 😃 I've opened a PR to add `last_download` and `last_upload` to the response of the `torrents.list` JSONRPC method. Both values behave the same, they represent the number of seconds since the last activity of that type (download, upload). Or -1 if we don't know.

Does that help?

**Comment by f4n4t** [comment]
Wow that was fast :smile: 
Thank you this is exactly what I was looking for.

**Comment by vktr** [comment]
Awesome! There's some issues with BuildJet and Docker rate limits right now - I'll merge the PR as soon as I can make it green, then after that it will build a beta version you can use. I'll ping when it's all done 😃 Feel free to hop into our [Discord](https://discord.gg/FNVVRzqJAG) if you need any help as well!

**Comment by vktr** [comment]
I've merged the PR and the stand-alone binaries are available here - https://github.com/porla/porla/actions/runs/5735946537. If you are using Docker, the `beta-latest` tag has also been updated so you can pull the latest version of that!
