### ISSUE TITLE
Is it possible to add a Trackerlist settings option for the webui.

### ISSUE THREAD

**Issue by hkthomas** [porla/porla#261]
For example, the latest tracker is automatically fetched from this address every day to add to a new seed.

https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt

**Comment by vktr** [comment]
Hi! There's nothing built in for this, but depending on how much Lua you know it it is certainly possible to write a plugin that does exacly what you want.

**Comment by hkthomas** [comment]
> Hi! There's nothing built in for this, but depending on how much Lua you know it it is certainly possible to write a plugin that does exacly what you want.

allright. ths
