### ISSUE TITLE
Error when loading workflow from docs: "module 'workflows' not found"

### ISSUE THREAD

**Issue by tlaerm** [porla/porla#289]
Hi everyone,
maybe this I have overlooked something obvious but I am stuck here: I want to write a workflow and to test whether workflows get executed at all I just put the example workflow from here: https://porla.org/plugins/workflows into the workflows dir. 

Then when I start porla the logs say:
```[error]   Failed to load workflow "/var/lib/porla/workflows/test.lua": lua: error: /var/lib/porla/workflows/test.lua:1: module 'workflows' not found:```

What am I getting wrong? Grateful for any pointers.

**Comment by vktr** [comment]
Hello!

Which version are you running? The docs follow the latest beta version (anything that is merged into main). If you're running the latest released version (0.35) I'd recomment updating, a bunch of stuff has been added and improved

**Comment by tlaerm** [comment]
Yes, running just ```latest```. I'll update and report back. Thank you for the quick reply.

**Comment by vktr** [comment]
Great! The Docker images are tagged `beta-latest` and the stand-alone binaries can be found under the _Actions_ tab, for any build targeting the `main` branch.

**Comment by tlaerm** [comment]
Changed the tag and it works. Thanks a lot for the quick help.
