### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by paxter** [porla/porla#296]
How is the status of this project? Start looked promising, but it's still an alpha stage and the [v1 project](https://github.com/orgs/porla/projects/1) didn't receive updates since mid 2023.

Is there an ETA for v1 or it's better to looking for another client?

**Comment by vktr** [comment]
Hi! It has received updates all through the summer, fall and winter - they have not been released as a real version however. If you want to run the latest version (with all the new updates) I recommend running the latest `beta-latest` Docker image, or the artifacts from the latest `main` branch build under Actions.

I should probably do a new release soon-ish though.

A v1 is planned but no real ETA. The only major thing missing is an updated web UI which I'm working on, but slowly.

**Comment by paxter** [comment]
Thanks for your reply @vktr :)

Yeah, I see the commits and you are still active developing this project. That is great and I'm still excited to see the first major version.
But I'm still missing something like a roadmap and the documentation looks a little bit outdated on some cases too.

At this point it's not very clear in which direction this project goes and where are the priorities. For example, I see you discovered the network share memory issues of libtorrent whose are still not solved.

Thanks a lot for keeping up this great project. :)

**Comment by vktr** [comment]
I'll see if I can put up a GitHub Project or something to keep track of everything.

Re: priorities - I think what we have now is a solid foundation - all that's missing currently is an improved web UI and that's where I will try to focus unless urgent issues come up :) I hope a v1 will be released before summer at least.

**Comment by paxter** [comment]
> I'll see if I can put up a GitHub Project or something to keep track of everything.

Sounds good, but please save your work if nobody else asked for something like this. Your answers are clear and that's all I wanted to know. :)
