### ISSUE TITLE
`GLIBC_2.28' not found

### ISSUE THREAD

**Issue by FlokiTV** [porla/porla#3]
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /content/node_modules/@porla/libtorrent/prebuilds/linux-x64/node-napi.node)

**Comment by FlokiTV** [comment]
![image](https://user-images.githubusercontent.com/11356271/102787949-a0f1ad00-4380-11eb-81e5-485b9c6bcfc3.png)

**Comment by vktr** [comment]
What OS are you running on?

**Comment by FlokiTV** [comment]
$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by vktr** [comment]
I don't remember exactly which OS I built the prebuilds on - but most likely Ubuntu 19.10. Do you have the latest `libc6` installed?

**Comment by FlokiTV** [comment]
![image](https://user-images.githubusercontent.com/11356271/102792252-05176f80-4387-11eb-97c5-dfc1c8c70fee.png)

**Comment by vktr** [comment]
Oh, just one minor away 😅 I'm in the process of updating the libtorrent bindings to support BitTorrent 2.0 so I'll make sure to build the bindings with a lower dependency for OS.

**Comment by FlokiTV** [comment]
Ok, thanks! I like this project.
Im working on vuejs web dashboard with file explorer

**Comment by vktr** [comment]
> Ok, thanks! I like this project.
> 
> Im working on vuejs web dashboard with file explorer 

Cool! Do you know about the existing dashboard? https://github.com/porla-contrib/dashboard

**Comment by FlokiTV** [comment]
Yes, but so simple hehe
