### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by smaugfm** [porla/porla#301]
I've just tried it in various ways and found it to be not working even on basic stuff: installing, workflows, etc.
Specifically:
- example [workflow](https://porla.org/plugins/workflows) does not load with an error
- there is no [button](https://porla.org/plugins/basics) to load custom plugins in the upper right corner of the UI
- "user" directive in [docker](https://porla.org/install/docker) compose does not force the insides of the container to create files with that user and group
- 
and much more

**Comment by vktr** [comment]
Hi! Are you running the latest beta, or the last release on GitHub? The latest beta is way ahead and we are many that run Porla without any issues, with both plugins and workflows.

**Comment by smaugfm** [comment]
Thank you for the response! 
I was actually running the latest Docker image, not sure what version it was. I see that you just made a big release an hour ago, I updated the docker image - the workflows issue is now gone. Should I stick with it or better build a new image from the latest commit on main?

**Comment by vktr** [comment]
I'm pretty sure you were running v0.35. Since that release I haven't made an official release, but many have been running the beta versions built from main. The latest release (v0.37) is just a real release of the latest main 😄 If that makes sense.

Happy it fixed your issues!

**Comment by smaugfm** [comment]
Perfect, thank you!
